version = 1

exclude_patterns = [
  "./src/assets",
  "./public",
  "./src/contracts",
  "./src/data",
  "./src/hooks",
  "./src/lib"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]